version: "3.7"

services:
  adguard_exporter:
    image: ebrianne/adguard-exporter:latest
    networks:
      - metrics 
    restart: always
    ports:
      - "9617:9617"
    env_file:
      - .env

networks:
  metrics:
    external: true
