version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/damon/docker:/home/damon/docker
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/damon/docker
    labels:
      traefik.enable: true
      traefik.http.routers.dockge.entrypoints: https
      traefik.http.services.dockge.loadbalancer.server.port: 5001
      traefik.http.routers.dockge.rule: Host(`dockge.$PRIMARY_DOMAIN`)
      
      
networks:
  traefik:
    external: true