version: '3.7'
services:
  svelte_website:
    image: ghcr.io/day-mon/damon.systems:main
    container_name: damon_systems_website
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.personal_website.rule: Host(`damon.systems`) || Host(`www.damon.systems`)
      traefik.http.routers.personal_website.entrypoints: https
      traefik.http.routers.personal_website.middlewares: www-personal_website-redirect
      traefik.http.services.personal_website.loadbalancer.server.port: 5010
      traefik.http.middlewares.www-personal_website-redirect.redirectregex.regex: https://www.damon.systems/(.*)
      traefik.http.middlewares.www-personal_website-redirect.redirectregex.replacement: https://damon.systems/$${1}
networks:
  traefik:
    external: true
