version: "3.9"

services:
  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    restart: always
    networks:
      - traefik
      - ollama
    labels:
      traefik.enable: true
      traefik.http.routers.chat.entrypoints: https
      traefik.http.services.chat.loadbalancer.server.port: 3000
      traefik.http.routers.chat.rule: Host(`chat.$PRIMARY_DOMAIN`)
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.scope: local
   # env_file:
    #  - .env
    command: ["next", "start", "-p", "3000"]

  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/app
    networks:
      - ollama

volumes:
  ollama_data:
    driver: local


networks:
  traefik:
    external: true
  ollama:
    name: ollama
