version: '3.7'

services:
    zipline:
      image: ghcr.io/diced/zipline
      container_name: zipline
      restart: always 
      env_file:
        - conf.env
      networks:
        - database
        - traefik
      volumes:
        - './.uploads:/zipline/uploads'
        - './.public:/zipline/public'
      labels:
        traefik.enable: true
        traefik.http.routers.upload.entrypoints: https
        traefik.http.services.upload.loadbalancer.server.port: 3000
        traefik.http.routers.upload.rule: Host(`upload.$PRIMARY_DOMAIN`)
        com.centurylinklabs.watchtower.enable: true
        com.centurylinklabs.watchtower.scope: local

      


networks:
  traefik:
    external: true
  database: 
    external: true
