version: '3.7'

services:
    database:
        image: postgres:14.0
        container_name: database
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
            - pgadmin
        expose:
            - 5432
    database-dev:
        image: postgres:14
        container_name: database-dev
        restart: unless-stopped
        env_file:
            - conf-dev.env
        volumes:
            - ./.data/postgres-dev/:/var/lib/postgresql/data/
        networks:
            - database
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/pgadmin:/var/lib/pgadmin
        networks:
            - pgadmin
            - database
            - traefik
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.pgadmin.rule: Host(`database.$PRIMARY_DOMAIN`)
            traefik.http.routers.pgadmin.entrypoints: https
            traefik.http.services.pgadmin.loadbalancer.server.port: 80
            traefik.http.routers.pgadmin.middlewares: authelia@docker

networks:
    database:
        name: database
    pgadmin:
        name: pgadmin
    traefik:
        external: true
