version: '3.7'

services:
    database:
        image: tensorchord/pgvecto-rs:pg14-v0.1.11 
        container_name: database
        restart: always 
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
    database-dev:
        image: postgres:14
        container_name: database-dev
        restart: always
        env_file:
            - conf-dev.env
        volumes:
            - ./.data/postgres-dev/:/var/lib/postgresql/data/
        networks:
            - database
        ports:
            - 5432:5432
networks:
    database:
        name: database
    traefik:
        external: true
