---
version: '3.7'

secrets:
  JWT_SECRET:
    file: ${PWD}/authelia/secrets/JWT_SECRET
  SESSION_SECRET:
    file: ${PWD}/authelia/secrets/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ${PWD}/authelia/secrets/STORAGE_ENCRYPTION_KEY
  SMTP_PASSWORD:
    file: ${PWD}/authelia/secrets/SMTP_PASSWORD

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: always
        env_file:
            - .env
        networks:
            - traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./traefik/traefik.yml:/etc/traefik/traefik.yml
            - ./traefik/data/letsencrypt/:/letsencrypt/
            - ./traefik/access.log:/access.log
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            traefik.enable: true
            traefik.http.routers.dashboard.rule: Host(`traefik.$PRIMARY_DOMAIN`)
            traefik.http.routers.dashboard.entrypoints: https
            traefik.http.routers.dashboard.service: api@internal
            traefik.http.routers.dashboard.middlewares: authelia@docker
            traefik.http.middlewares.global-compress.compress: true
        command: 
            - '--api'
            - '--providers.docker=true'

    authelia:
        image: authelia/authelia:v4.38.0-beta2
        container_name: authelia
        user: 1001:1001
        depends_on:
            - traefik
        volumes:
            - ./authelia:/config
        networks:
            - traefik
            - authelia
            - mail
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.authelia.rule=Host(`auth.$PRIMARY_DOMAIN`)'
            - 'traefik.http.routers.authelia.entrypoints=https'
            - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.$PRIMARY_DOMAIN'  # yamllint disable-line rule:line-length
            - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
            - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
            - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
        expose:
            - 9091
        restart: always
        secrets: [JWT_SECRET, SESSION_SECRET, STORAGE_ENCRYPTION_KEY, SMTP_PASSWORD]
        environment:
            TZ: "America/New_York"
            AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
            AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
            AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
            AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD
        healthcheck:
            disable: true

    authelia_redis:
        image: redis:latest
        container_name: authelia-redis-cache
        restart: always
        depends_on:
            - authelia
        networks:
            - authelia

networks:
    traefik:
        name: traefik
    authelia:
        name: authelia
    mail:
        external: true
