global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: info

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:   
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver: default
                domains:
                    - main: 'montague.im'
                      sans:
                          - 'database.montague.im'
                          - 'traefik.montague.im'
                          - 'map.montague.im'
                          - 'schoolbot.dev'
                          - 'home.montague.im'
                          - 'grafana.montague.im'
                          - 'guard.montague.im'
                          - 'guard-setup.montague.im'
                          - 'damon.systems'
                          - 'www.damon.systems'
                          - 'public.montague.im'
                          - 'secure.montague.im'
                          - 'auth.montague.im'
                          - 'prometheus.montague.im'
                          - 'johnstown.schoolbot.dev'
                          - 'vault.montague.im'
                          - 'upload.montague.im'
                          - 'warden.montague.im'
                          - 'miner.montague.im'
                          - 'surreal.montague.im'
                          - 'montague.im'
            middlewares:
                - global-compress@docker
                  
providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        directory: '/configs'

api:
    dashboard: true

certificatesResolvers:
    default:
        acme:
          #caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: damon@montague.im
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http

