global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: info

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver: default
                domains:
                    - main: 'schoolbot.dev'
                      sans:
                          - 'database.schoolbot.dev'
                          - 'traefik.schoolbot.dev'
                          - 'damon.systems'
                          - 'www.damon.systems'

providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        directory: '/configs'

api:
    dashboard: true

certificatesResolvers:
    default:
        acme:
            #caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: damon@montague.im
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http
