global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: info 
    format: common

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver: default
                domains:
                    - main: 'montague.im'
                      sans:
                          - 'database.montague.im'
                          - 'traefik.montague.im'
                          - 'map.montague.im'
                          - 'home.montague.im'
                          - 'grafana.montague.im'
                          - 'guard.montague.im'
                          - 'sports.schoolbot.dev'
                          - 'guard-setup.montague.im'
                          - 'auth.montague.im'
                          - 'uptime.montague.im'
                          - 'cloud.montague.im'
                          - 'office.montague.im'
                          - 'docker.montague.im'
                          - 'prometheus.montague.im'
                          - 'watchtower.montague.im'
                          - 'accuribet.win'
                          - 'mock.accuribet.win'
                          - 'mapi.accuribet.win'
                          - 'api.accuribet.win'
                          - 'jupyter.montague.im'
                          - 'mineos.montague.im'
                          - 'vault.montague.im'
                          - 'upload.montague.im'
                          - 'warden.montague.im'
                          - 'miner.montague.im'
                          - 'wings.montague.im'
                          - 'games.montague.im'
                          - 'surreal.montague.im'
                          - 'schoolbot.dev'
                          - 'schoolapi.schoolbot.dev'
                          - 'damon.systems'
                          - 'www.damon.systems'
            middlewares:
                - global-compress@docker

providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        directory: '/configs'


api:
    dashboard: true

certificatesResolvers:
    default:
        acme:
          #caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: damon@montague.im
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http

