version: '3.7'

services:
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        restart: unless-stopped
        ports:
          - 3000:3000
        volumes:
            - ./.data/grafana/:/var/lib/grafana/
            - ./grafana.ini:/etc/grafana/grafana.ini
        networks:
            - grafana-database
            - metrics
            - mail
        depends_on:
            - grafana-database
  
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: unless-stopped
        ports:
            - 9090:9090
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=1y'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./.data/prometheus/:/prometheus/data/
        networks:
            - metrics
  

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        restart: unless-stopped
        command: --path.rootfs=/host
        ports:
            - 9100:9100
        pid: host
        volumes:
            - /:/host:ro,rslave
        networks:
            - metrics

    loki:
        image: grafana/loki
        container_name: loki
        restart: unless-stopped
        command: -config.file=/etc/loki/local-config.yaml
        ports: 
            - 127.0.0.1:3100:3100
        networks:
            - metrics
        volumes:
            - ./loki.yml:/etc/loki/docker-config.yaml
    promtail:
        image: grafana/promtail
        container_name: promtail
        restart: unless-stopped
        command: -config.file=/etc/promtail/docker-config.yml
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers
            - ./promtail-config.yml:/etc/promtail/docker-config.yml
        networks:
            - metrics
    grafana-database:
        image: postgres:latest
        container_name: postgres-database
        restart: unless-stopped
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - grafana-database

networks:
    grafana:
        name: grafana
    metrics:
        name: metrics
    mail:
        external: true
    grafana-database:
        name: grafana-database
