global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: schoolbot/prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          machine: schoolbot

  - job_name: schoolbot/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100', 'cadvisor:8080']
        labels:
          machine: schoolbot

  - job_name: schoolbot/traefik
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8080']
        labels:
          machine: schoolbot


  - job_name: watchtower
    scrape_interval: 5s
    bearer_token: EXAMPLE
    static_configs:
      - targets: ['watchtower:8080']

