global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets: ['127.0.0.1:9090']

    - job_name: metrics
      scrape_interval: 5s
      static_configs:
          - targets: ['node-exporter:9100', 'cadvisor:8080']

    - job_name: traefik
      scrape_interval: 5s
      static_configs:
          - targets: ['traefik:8080']
