version: '3.7'

services:
    forge_minecraft:
        image: itzg/minecraft-server:java8
        container_name: forge_minecraft_server
        restart: unless-stopped
        env_file: 
            - config.env
        volumes: 
            - ./modpacks:/modpacks:rw
            - ./data:/data
        networks: 
            - minecraft
        ports:
            - 25565:25565

networks:
    forge_minecraft:
        name: forge_minecraft