version: '3.1'
services:
  schoolbot:
    image: ghcr.io/tykoooo/school-bot-remastered:master
    container_name: schoolbot
    volumes: 
      - ./schoolbot.cfg:/home/schoolbot/config/schoolbot.cfg
    environment: 
    # The bot will run on whatever timezone you select
      - TZ=America/New_York
