version: "3"
services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update --http-api-token EXAMPLE

networks:
  traefik:
    external: true
