version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    networks:
      - traefik
      - database
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - immich-redis
      - typesense
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.immich_server.entrypoints: https
      traefik.http.services.immich_server.loadbalancer.server.port: 3001
      traefik.http.routers.immich_server.rule: Host(`immich.$PRIMARY_DOMAIN`)
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.scope: local
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    networks:
      - database
      - immich      
    depends_on:
      - immich-redis
      - typesense
    restart: always
    labels:
        com.centurylinklabs.watchtower.enable: true
        com.centurylinklabs.watchtower.scope: local

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich      
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.scope: local



  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    networks:
      - immich   
    restart: always

  immich-redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - immich   
 
volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  traefik:
    external: true
  database:
    external: true
  immich:
    name: immich
  
