version: '3.7'

services:
    adguard:
        image: adguard/adguardhome:edge
        container_name: adguard
        restart: always
        volumes:
          - ./workdir:/opt/adguardhome/work
          - ./confdir:/opt/adguardhome/conf
        ports:
          - 53:53/tcp
          - 53:53/udp
          - 81:80/tcp
          - 853:853/tcp
          - 853:853/udp
          - 5810:3000
