version: '3.7'

services:
    adguard:
        image: adguard/adguardhome
        container_name: adguard
        restart: always
        networks:
          - traefik
          - metrics
        volumes:
          - ./workdir:/opt/adguardhome/work
          - ./confdir:/opt/adguardhome/conf
        ports:
          - 53:53/tcp
          - 53:53/udp
          - 67:67/udp
          - 68:80/udp
          - 81:80/tcp
          - 853:853/tcp
          - 853:853/udp
        labels:
          traefik.enable: true
          traefik.http.routers.adguard.entrypoints: https
          traefik.http.services.adguard.loadbalancer.server.port: 3000
          traefik.http.routers.adguard.rule: Host(`guard.$PRIMARY_DOMAIN`)
          #traefik.http.routers.adguard.middlewares: authelia@docker



networks:
  traefik:
    external: true
  metrics:
    external: true
