version: '3'

services:
    adguard:
        image: adguard/adguardhome:edge
        container_name: adguard
        restart: always
        volumes:
          - ./workdir:/opt/adguardhome/work
          - ./confdir:/opt/adguardhome/conf
        network_mode: "host" 
