global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: info 
    format: common
    

accessLog:
    filePath: "./access.log"
    format: common

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                 certResolver: cloudflare
                 domains:
                     - main: 'montague.im'
                       sans:
                           - '*.montague.im'
                     - main: 'damon.systems'
                       sans:
                           - '*.damon.systems'
                     - main: 'accuribet.win'
                       sans:
                           - '*.accuribet.win'
                     - main: 'emotionalhealingsolutions.com'
                       sans:
                           - '*.emotionalhealingsolutions.com'



providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        

api:
    dashboard: true

experimental:
  plugins:
    traefik-get-real-ip:
      moduleName: "github.com/Paxxs/traefik-get-real-ip"
      version: "v1.0.3"

certificatesResolvers:
    default:
        acme:
          #caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: damon@montague.im
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http
    cloudflare:
        acme:
            # testing server
            # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: damon@montague.im
            storage: /letsencrypt/acme.json
            dnsChallenge:
                provider: cloudflare
                delayBeforeCheck: 120
                resolvers:
                    - opal.ns.cloudflare.com
                    - trace.ns.cloudflare.com
