version: '3.7'

services:
    minecraft:
        image: itzg/minecraft-server:latest
        #image: itzg/minecraft-server:java8
        container_name: minecraft_server
        env_file:
            - config.env
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        networks:
            - minecraft
            - traefik
        labels:
          traefik.enable: true
          traefik.http.routers.mc.rule: Host(`map.montague.im`)
          traefik.http.routers.mc.entrypoints: https
          traefik.http.services.mc.loadbalancer.server.port: 8100
        ports:
            - 25565:25565

networks:
    traefik:
      external: true
    minecraft:
        name: minecraft
