version: '3.7'

services:
    minecraft:
        image: itzg/minecraft-server:latest
        #image: itzg/minecraft-server:java8
        container_name: minecraft_server
        restart: unless-stopped
        env_file:
            - config.env
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        networks:
            - minecraft
        ports:
            - 25565:25565

networks:
    minecraft:
        name: minecraft
