version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./downloads/movies:/media/movies/
      - ./downloads/shows:/media/shows
    networks:
      - jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./prowlarr/config:/config
      - ./downloads/:/downloads/
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - jellyfin
    depends_on:
      - arch-qbittorrentvpn
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /radarr/config:/config
      - ./downloads/:/downloads/
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - arch-qbittorrentvpn
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./sonarr/config:/config
      - ./downloads/:/downloads/
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - arch-qbittorrentvpn
  arch-qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    volumes:
      - './qbittorrentvpn/config/:/config'
      - './downloads:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
      - 8118:8118 
    env_file:
      - qbit.env
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ./overseerr:/app/config
    restart: unless-stopped
    networks:
      - mail


networks:
  jellyfin:
    name: jellyfin
  mail:
    name: mail