version: '3.7'

services:
    kuma:
      image: louislam/uptime-kuma
      container_name: uptime-kuma
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./.data:/app/data
      networks:
        - traefik
        - mail
      labels:
        traefik.enable: true
        traefik.http.routers.kuma.rule: Host(`uptime.$PRIMARY_DOMAIN`)
        traefik.http.routers.kuma.entrypoints: https
        traefik.http.services.kuma.loadbalancer.server.port: 3001

networks:
  traefik:
    external: true
  mail:
    external: true
