---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings



# colors: ['slate', 'gray', 'zinc', 'neutral', 'stone', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose', 'red', 'white']

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

theme: dark # or light
color: gray
title: Homepage
