
version: '3.7'

services:
    schoolapi:
        image: ghcr.io/day-mon/pitt-api-final:main
        container_name: schoolapi
        restart: unless-stopped
        networks:
            - traefik
        labels: 
            traefik.enable: true
            traefik.http.routers.schoolapi.rule: Host(`schoolapi.damon.systems`)
            traefik.http.routers.schoolapi.entrypoints: https
            traefik.http.services.schoolapi.loadbalancer.server.port: 8080

networks:
    traefik:
        external: true
