version: '3.7'
services:
   schoolbot_website:
        image: nginx:latest
        container_name: schoolbot_website
        restart: unless-stopped
        networks:
            - traefik
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./schoolbot/html:/usr/share/nginx/html
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.schoolbot_website.rule: Host(`schoolbot.dev`) || Host(`www.schoolbot.dev`)
            traefik.http.routers.schoolbot_website.entrypoints: https
            traefik.http.routers.schoolbot_website.middlewares: www-schoolbot_website-redirect
            traefik.http.services.schoolbot_website.loadbalancer.server.port: 80
            traefik.http.middlewares.www-schoolbot_website-redirect.redirectregex.regex: https://www.schoolbot.dev/(.*)
            traefik.http.middlewares.www-schoolbot_website-redirect.redirectregex.replacement: https://schoolbot.dev/$${1}
   montague:
        image: nginx:latest
        container_name: montague
        restart: unless-stopped
        networks:
            - traefik
        volumes:
            - ./nginx_montague.conf:/etc/nginx/nginx.conf:ro
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.montague.rule: Host(`montague.im`) || Host(`www.montague.im`)
            traefik.http.routers.montague.entrypoints: https
            traefik.http.services.montague.loadbalancer.server.port: 80
networks:
    traefik:
        external: true
